### ISSUE TITLE
Bubble socket events to router

### ISSUE THREAD

**Issue by Wildhoney** [Wildhoney/EmberSockets#16]

**Comment by THuRStoN** [comment]
I'd been looking at the commits but unfortunately I can't find anything related to this enhancement. Is there any progress?
The procedure is similar to what is done in _listen & _update but processing associated routes in case the controller didn't respond to the event. 

Thanks for any advise on how to do implement it.

Thanks for any advise.

**Comment by Wildhoney** [comment]
Unfortunately I haven't implemented this feature yet &ndash; and I've not been keeping up with Ember all that much. From the controller, what is the optimal way of determining its associated route? If we can determine that reliably, then we can bubble the event to its route.

If you'd like to have a dig around finding the associated route, then I'm happy to help you folks it! :+1:

**Comment by THuRStoN** [comment]
I think (maybe I'm wrong) a controller doesn't know its associated route directly. Anyway I'll investigate :+1:

**Comment by Wildhoney** [comment]
Thanks, Alex :+1: Let us know what you find, as this has been open for a while now. It would be nice to have it resolved.
